theme: jekyll-theme-tactile
title: worknrole.github.io
description: > 
baseurl: ""
url: "http://127.0.0.1:4000"
github_username:  worknrole

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
