theme: jekyll-theme-tactile
title: worknrole.github.io
description: > 
baseurl: ""
url: "http://127.0.0.1:4000"
github_username:  worknrole

coverurl: "assets/img/cover/"
designurl: "https://github.com/worknrole/android-design/tree/master/design/designapp/src/main/java/com/worknrole/design/"
externalsampleurl: "https://github.com/worknrole/android-sample/blob/master/sample/sample-project/src/main/java/com/worknrole/sample/externallibraries/"
testsampleurl: "https://github.com/worknrole/android-sample/tree/master/sample/sample-project/src/"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
